export default {
  user: {},
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  notes: '',
  value: '',
  userId: '',
  customerId: '',
  productOrPackage: null,
  package: {},
  productsSelected: [],
  products: [],
}
