export default {
  packages: {
    permission: null,
    activated: true,
    path: '/quote/packages/index',
    name: 'qquote.admin.packages',
    page: () => import('@imagina/qquote/_pages/admin/packages/index'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminPackages',
    icon: 'fas fa-box',
    authenticated: true,
  },
  products: {
    permission: 'iquote.products.index',
    activated: true,
    path: '/quote/products/index',
    name: 'qquote.admin.products',
    page: () => import('@imagina/qquote/_pages/admin/products/index'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminProducts',
    icon: 'fab fa-elementor',
    authenticated: true,
  },
  productsCreate: {
    permission: 'iquote.products.create',
    activated: true,
    path: '/quote/products/create',
    name: 'qquote.admin.productsCreate',
    page: () => import('@imagina/qquote/_pages/admin/products/create'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminProducts',
    icon: 'fab fa-elementor',
    authenticated: true,
  },
  productsEdit: {
    permission: 'iquote.products.edit',
    activated: true,
    path: '/quote/products/edit/:id',
    name: 'qquote.admin.productsEdit',
    page: () => import('@imagina/qquote/_pages/admin/products/edit'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminProducts',
    icon: 'fab fa-elementor',
    authenticated: true,
  },
  characteristicEdit: {
    permission: 'iquote.characteristics.edit',
    activated: true,
    path: '/quote/characteristics/edit/:characteristicId',
    name: 'qquote.admin.characteristicEdit',
    page: () => import('@imagina/qquote/_pages/admin/characteristics/edit'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminCharacteristics',
    icon: 'fas fa-list-ol',
    authenticated: true,
  },
  quotes: {
    permission: 'iquote.quotes.index',
    activated: true,
    path: '/quote/quotes',
    name: 'qquote.admin.quotes',
    page: () => import('@imagina/qquote/_pages/admin/quotes/index'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminQuotes',
    icon: 'fas fa-calculator',
    authenticated: true,
  },
  quotesCreate: {
    permission: 'iquote.quotes.create',
    activated: true,
    path: '/quote/quotes/create',
    name: 'qquote.admin.quotesCreate',
    page: () => import('@imagina/qquote/_pages/admin/quotes/create'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminQuotes',
    icon: 'fas fa-calculator',
    authenticated: true,
  },
  quotesShow: {
    permission: 'iquote.quotes.index',
    activated: true,
    path: '/quote/quotes/:id',
    name: 'qquote.admin.quotesShow',
    page: () => import('@imagina/qquote/_pages/admin/quotes/show'),
    layout: () => import('@imagina/qsite/_layouts/master.vue'),
    title: 'qquote.sidebar.adminQuotes',
    icon: 'fas fa-calculator',
    authenticated: true,
  },
}
